Various corrections from static analysis
KallistiOS/KallistiOS pull request #204
Opened 2023-05-20 03:57 UTC by QuzarDC

I've tried to separate each into it's own commit under this to make it easier to pick and choose/test and verify. All of these were minor issues found via cppcheck or gcc's static analysis system. Possible memory leaks, overwriting values, null derefs, etc. Along the way expanded a few comments and such.

Leaving as draft as I wanted to do this for a few more files, and perhaps some of the changes could get reviewed in the meantime.

The only functional change was the placement of an assert for thread wrap-around. Before, an if statement in thd_create_ex prevented threads from being created with negative tids. However, thd_next_free seemed to presume that it would wrap-around freely. thd_create_ex no longer breaks with negatives, but thd_next_free will assert on rollover instead. This seems like more clear error behavior than just not spinning up new threads. Since TIDs are never used to store negative numbers for errors, I would propose to also update tid_t to be based on an unsigned int to push further away the possibility of running out.

2023-06-02 04:05 UTC, andressbarajas commented
https://developers.redhat.com/articles/2023/05/31/improvements-static-analysis-gcc-13-compiler#

Just found this link. Is this what you used?

2023-06-03 01:36 UTC, QuzarDC commented
> https://developers.redhat.com/articles/2023/05/31/improvements-static-analysis-gcc-13-compiler#
> 
> Just found this link. Is this what you used?

Yes, some was from that, others from cppcheck. There were still quite a few from -fanalyze and a lot that were false positives (where, for instance, it just couldn't see the full scope that would show that the error couldn't ever be triggered). I figured that once this got merged I'd go ahead and look for more with the same toolset, perhaps with some changed options.

2023-06-03 02:18 UTC, ljsebald requested changes

2023-06-03 02:18 UTC, ljsebald commented on kernel/arch/dreamcast/fs/fs_vmu.c
> +    if(dh == NULL) return NULL;
```suggestion
    if(!(dh = malloc(sizeof(vmu_dh_t))))
        return NULL;
```

2023-06-03 02:18 UTC, ljsebald commented on kernel/arch/dreamcast/fs/fs_vmu.c
> +    if(dh == NULL) return NULL;
```suggestion
    if(!(dh = malloc(sizeof(vmu_dh_t))))
        return NULL;
```

2023-06-03 02:18 UTC, ljsebald commented on kernel/arch/dreamcast/fs/fs_vmu.c
> +    if(fd == NULL) return NULL;
```suggestion
    if(!(fd = malloc(sizeof(vmu_fh_t))))
        return NULL;
```

2023-06-03 02:18 UTC, ljsebald commented on kernel/arch/dreamcast/kernel/mmu.c
> +    if(cont == NULL) return NULL;
```suggestion
    if(cont == NULL)
        return NULL;
```

2023-06-03 02:18 UTC, ljsebald commented on kernel/fs/fs_ramdisk.c
> +    if(f == NULL) return NULL;
```suggestion
    if(!(f = (rd_file_t *)malloc(sizeof(rd_file_t))))
        return NULL;
```

2023-06-03 02:18 UTC, ljsebald commented on kernel/fs/fs_ramdisk.c
>      rootdir = (rd_dir_t *)malloc(sizeof(rd_dir_t));
```suggestion
    if(!(rootdir = (rd_dir_t *)malloc(sizeof(rd_dir_t))))
        return -1;
```

2023-06-03 02:18 UTC, ljsebald commented on kernel/fs/fs_ramdisk.c
> +    if(rootdir == NULL) return -1;
```suggestion
```

2023-06-03 02:34 UTC, ljsebald approved these changes

2023-06-03 02:35 UTC, merged