Added Quzar's VMUBeep as an Example
KallistiOS/KallistiOS pull request #214
Opened 2023-05-23 20:51 UTC by gyrovorbis

Quzar's VMUBeep is an incredibly useful tool that allows you to easily send raw maple buzzer commands to a VMU. It was just able to help us do some R&D on how the buzzer behaves with the 6Mhz VMU clock versus the slower ones used in standalone mode.

- integrated the tool into KOS as an example
- modifified a bunch of the comments, now that we actually know what these raw bytes mean
- trivial formatting changes
- uintN types -> uintN_t types
- removed warnings

2023-05-23 23:59 UTC, ljsebald requested changes
A couple of things I'd like to see fixed before merging this:

1. Fix the Copyright notices to be correct. They should be of the following form, technically speaking: `Copyright (C) Year Author` (and only one author per line)
2. Fix the Makefile for the example to match other examples (i.e, using `kos-cc` instead of `$(KOS_CC)` and other such things
3. Change Tabs to 4 spaces and generally fix formatting in the code (for instance, the curly brace on the `for(;;)` loop, spaces after `while` and `if`, missing spaces between `)` and `{` on some conditionals, missing spaces between conditional blocks, etc. Also, the formatting on the header comment needs to be fixed (there shouldn't be tabs there either).
4. It'd also be nice if the example included the header files it actually needs, rather than just including `<kos.h>`. But that's more my personal preference there...

2023-05-24 02:10 UTC, gyrovorbis commented
Sounds good. I think got them all.

I actually thought that if multiple people contributed at the same time to a file, they were supposed to be comma separated. WHOOPS!

2023-05-26 01:23 UTC, ljsebald requested changes

2023-05-26 01:23 UTC, ljsebald commented on examples/dreamcast/vmu/vmu_beep/Makefile
> +# (C) 2008 Donald Haase
```suggestion
# Copyright (C) 2008 Donald Haase

```

2023-05-26 01:23 UTC, ljsebald commented on examples/dreamcast/vmu/vmu_beep/beep.c
> +*/
```suggestion
/*  KallistiOS ##version##

    beep.c
    Copyright (C) 2004 SinisterTengu
    Copyright (C) 2008 Donald Haase

*/
```

2023-05-26 01:23 UTC, ljsebald commented on examples/dreamcast/vmu/vmu_beep/beep.c
> +        (void(*)(uint8_t, uint32_t))arch_exit);
```suggestion
    /* If the face buttons are all pressed, exit the app */
    cont_btn_callback(0, CONT_START | CONT_A | CONT_B | CONT_X | CONT_Y,
                      (void(*)(uint8_t, uint32_t))arch_exit);
```

2023-05-26 01:23 UTC, ljsebald commented on examples/dreamcast/vmu/vmu_beep/beep.c
> +    for (;;) {
I meant remove the spaces, not add them.
```suggestion
    for(;;) {
```

2023-05-26 01:23 UTC, ljsebald commented on examples/dreamcast/vmu/vmu_beep/beep.c
> +        while (!dev) {
```suggestion
        while(!dev) {
```

2023-05-26 01:23 UTC, ljsebald commented on examples/dreamcast/vmu/vmu_beep/beep.c
> +        while (!vmudev) {
```suggestion
        while(!vmudev) {
```

2023-05-26 01:23 UTC, ljsebald commented on examples/dreamcast/vmu/vmu_beep/beep.c
> +            if (i == count)
```suggestion
        while(count <= 7) {
            if(i == count)
```

2023-05-26 01:23 UTC, ljsebald commented on examples/dreamcast/vmu/vmu_beep/beep.c
> +            printf("Beep Stopped!\n");
```suggestion
        if((state->buttons & CONT_DPAD_LEFT) && (rel_buttons & CONT_DPAD_LEFT)) {
            if (i > 0) i--;
        }

        if((state->buttons & CONT_DPAD_RIGHT) && (rel_buttons & CONT_DPAD_RIGHT)) {
            if (i < 7) i++;
        }

        if((state->buttons & CONT_DPAD_UP) && (rel_buttons & CONT_DPAD_UP)) {
            if (n[i] < 15) n[i]++;
        }

        if((state->buttons & CONT_DPAD_DOWN) && (rel_buttons & CONT_DPAD_DOWN)) {
            if (n[i] > 0) n[i]--;
        }

        if((state->buttons & CONT_A) && (rel_buttons & CONT_A)) {
            effect = (n[0] << 28) + (n[1] << 24) + (n[2] << 20) + (n[3] << 16) +
                     (n[4] << 12) + (n[5] << 8) + (n[6] << 4) + (n[7] << 0);

            vmu_beep_raw(vmudev, effect);
            printf("VMU Beep: 0x%lx!\n", effect);
        }

        if((state->buttons & CONT_B) && (rel_buttons & CONT_B)) {
            vmu_beep_raw(vmudev, 0x00000000);
            printf("Beep Stopped!\n");
```

2023-05-26 01:35 UTC, gyrovorbis commented
Give me a sec to verify the example is still good to go.

2023-05-26 01:39 UTC, gyrovorbis commented
Everything is fine here! Built and tested!

2023-05-26 02:11 UTC, ljsebald commented on examples/dreamcast/vmu/vmu_beep/beep.c
> +		/* Store current button states + buttons which have been released. */
One last one that I just noticed...
```suggestion
        /* Store current button states + buttons which have been released. */
```

2023-05-26 02:13 UTC, ljsebald approved these changes

2023-05-26 02:14 UTC, merged