Move vector.h from addons to core.
KallistiOS/KallistiOS pull request #218
Opened 2023-05-26 06:24 UTC by jpeach

The core matrix API depends on the typedefs in vector.h, which currently lives in the addons tree. This change moves these typed back to the core kernel tree so that we don't have a dependency from addons back to the kernel.

2023-05-27 03:19 UTC, ljsebald requested changes

2023-05-27 03:19 UTC, ljsebald commented on kernel/arch/dreamcast/include/dc/vector.h
> +/** \file   kos/vector.h
```suggestion
/** \file   dc/vector.h
```

2023-05-27 03:19 UTC, ljsebald commented on kernel/arch/dreamcast/include/dc/vector.h
> +    \headerfile kos/vector.h
```suggestion
    \headerfile dc/vector.h
```

2023-05-27 03:19 UTC, ljsebald commented on kernel/arch/dreamcast/include/dc/vector.h
> +    \headerfile kos/vector.h
```suggestion
    \headerfile dc/vector.h
```

2023-05-27 03:19 UTC, ljsebald commented on kernel/arch/dreamcast/include/dc/vector.h
> +    \headerfile kos/vector.h
```suggestion
    \headerfile dc/vector.h
```

2023-05-27 03:19 UTC, ljsebald commented on kernel/arch/dreamcast/include/dc/vector.h
> +    elsewhere, as well.
```suggestion
    This file provides a few primitive data types that are useful for 3D
    graphics.
```

2023-05-27 03:19 UTC, ljsebald commented on addons/include/kos/vector.h
> +    This file is provided for backwards compatibility. New code should include <dc/vector.h> directly.
```suggestion
    This file is provided for backwards compatibility. New code should include
    <dc/vector.h> directly.
```

2023-05-28 01:48 UTC, jpeach commented
Thanks @ljsebald. Sorry, it was a bit lazy to miss cleaning up those comments!

2023-05-29 00:49 UTC, ljsebald approved these changes

2023-05-29 00:50 UTC, merged