Add Rumble Example
KallistiOS/KallistiOS pull request #227
Opened 2023-05-30 08:10 UTC by QuzarDC

Adding an example for using the purupuru/JumpPack/rumble device. This is a recreation and enhancement of SinisterTengu's lost original which in turn was made into a tester for the vmu's beep by me, which was in turn added to examples by @gyrovorbis.

I've enhanced it over the original by allowing the controller or rumble to be disconnected and reconnected without having to restart the test (facilitating easier swapping and providing examples of such loops).

I've additionally updated the driver to de-duplicate the composed and raw versions of the rumble.

Before moving this out of draft, I may be adding a second mode which allows for a similar experimentation with the different composed effects elements.

2023-05-31 06:03 UTC, gyrovorbis commented
Hell yeah! Much needed after the VMU beep one!

2023-06-03 01:39 UTC, ljsebald requested changes

2023-06-03 01:39 UTC, ljsebald commented on examples/dreamcast/rumble/rumble.c
> +    for(;!(rel_buttons & CONT_START);) {
```suggestion
    while(!(rel_buttons & CONT_START)) {
```

2023-06-03 01:39 UTC, ljsebald commented on examples/dreamcast/rumble/rumble.c
> +        for(count = 0; count <= 7; count++, w.x+=25.0f) {
```suggestion
        for(count = 0; count <= 7; count++, w.x += 25.0f) {
```

2023-06-03 02:04 UTC, ljsebald commented on doc/CHANGELOG
> +- DC  Add example for VMU speaker use [DH] [FG]
```suggestion
- DC  Add example for VMU speaker use [DH && FG]
```

2023-06-03 02:05 UTC, ljsebald approved these changes

2023-06-03 02:06 UTC, merged