Added Spinlock Example/Test
KallistiOS/KallistiOS pull request #275
Opened 2023-08-25 04:07 UTC by gyrovorbis

Upon constructing a test scenario for @ljsebald's last PR (addition of `spinlock_trylock()`), it was decided that we may as well flesh the test case out into an example for KOS. 

The example is located in `kos/examples/dreamcast/basic/theading/spinlock_test`. It spawns 10 threads which all compete for acquiring a spinlock using both `spinlock_trylock()` and `spinlock_lock()`. It also shows off doing something "useful" while `spinlock_trylock()` fails.

2023-08-25 15:57 UTC, ljsebald requested changes

2023-08-25 15:57 UTC, ljsebald commented on examples/dreamcast/basic/threading/spinlock_test/Makefile
> +# (c) 2023 Falco Girgis
```suggestion
# Copyright (C) 2023 Falco Girgis
```

2023-08-25 15:57 UTC, ljsebald commented on examples/dreamcast/basic/threading/spinlock_test/spinlock_test.c
> +   (c) 2023 Falco Girgis
Not sure why I'm being credited here...

```suggestion
   Copyright (C) 2023 Falco Girgis
```

2023-08-25 15:57 UTC, ljsebald commented on examples/dreamcast/basic/threading/spinlock_test/spinlock_test.c
> +    unsigned fibres=0, fibn=0;
```suggestion
    unsigned fibres = 0, fibn = 0;
```

2023-08-25 15:57 UTC, ljsebald commented on examples/dreamcast/basic/threading/spinlock_test/spinlock_test.c
> +        /* Optionally let the other threads have some time too. */
```suggestion
        /* Let the other threads have some time too. */
```

2023-08-25 15:57 UTC, ljsebald commented on examples/dreamcast/basic/threading/spinlock_test/spinlock_test.c
> +    };
```suggestion
        threads[i] = thd_create(0, thd, (void *)(i + 1));
    }
```

2023-08-25 15:57 UTC, ljsebald commented on examples/dreamcast/basic/threading/spinlock_test/spinlock_test.c
> +    return (void*)(fibn - 1);
```suggestion
    return (void *)(fibn - 1);
```

2023-08-30 20:54 UTC, gyrovorbis commented
Rebuilt after addressing PR changes, everything looks good.
`
..............
Thread[6] yielding the lock
Thread[6] locking the lock
Thread[6] locked the lock
Thread[6] unlocking the lock
Thread[6] returned.
Thread[7] returned.
Thread[8] trylock succeeded!
Thread[8] calculated the 38th fibonacci number while waiting: 39088169
Thread[10] still trying the lock!
Thread[8] yielding the lock
Thread[8] locking the lock
Thread[8] locked the lock
Thread[8] unlocking the lock
Thread[8] returned.
Thread[9] returned.
Thread[10] trylock succeeded!
Thread[10] calculated the 39th fibonacci number while waiting: 63245986
Thread[10] yielding the lock
Thread[10] locking the lock
Thread[10] locked the lock
Thread[10] unlocking the lock
Thread[10] returned.
Threads finished and calculated 339 fibonacci numbers while they waited!


***** SPINLOCK TEST SUCCESS! *****
`

2023-08-30 21:50 UTC, ljsebald approved these changes

2023-08-30 21:50 UTC, merged