Initial C11 libatomic GCC builtin implementation
KallistiOS/KallistiOS pull request #301
Opened 2023-09-09 03:47 UTC by gyrovorbis

This PR is to add the remaining GCC builtins required to enable all of C11's atomics, located in `<stdatomic.h>`. The majority of the builtins for primitive types are given to us by the compiler with `-matomic-model=soft-imask`; however, this evidently does not cover 64-bit (long long) primitive types nor does it cover the generic cases for atomic structures and buffers.

I've implemented these missing builtins, and I've implemented the 64-bit primitive back-ends using generic macros to generate the function calls, just in case we find anything else missing or wind up wanting to handle all primitive atomics by ourselves. 

- Initial implementation should cover everything C99 atomics entail, located at kernel/libc/c11/atomics.c

2023-09-11 17:00 UTC, gyrovorbis commented
@ljsebald I was pondering some stuff last night and wanted to double check something with you real quick.

The C11 atomics API lets you query the implementation via `atomic_is_lock_free()` on an atomic to determine whether it "locks" or not. The default implementation for the stuff GCC is giving us via `-matomic-model=soft-imask` is all returning `true` there, so that model is clearly considered to be lock-free.

The question, though, is now that we're using spinlocks for the generic-case, is that still considered to be a "lock-free" implementation by the C standard, since it's technically non-blocking or do I need to modify that symbol to return `false` for the generic case?

2023-09-11 20:15 UTC, ljsebald commented
> @ljsebald I was pondering some stuff last night and wanted to double check something with you real quick.
> 
> The C11 atomics API lets you query the implementation via `atomic_is_lock_free()` on an atomic to determine whether it "locks" or not at runtime. The default implementation for the stuff GCC is giving us via `-matomic-model=soft-imask` is all returning `true` there, so that model is clearly considered to be lock-free.
> 
> The question, though, is now that we're using spinlocks for the generic-case, is that still considered to be a "lock-free" implementation by the C standard, since it's technically non-blocking or do I need to modify that symbol to return `false` for the generic case?

I'd imagine it wouldn't be proper to say that our implementation is lock free when it isn't. In the grand scheme of things, does it matter? Probably not... But to be proper, it should probably be the case that for any object that would trigger the spinlock case that it should say false for it being lock-free.

2023-09-11 23:05 UTC, gyrovorbis commented
> > @ljsebald I was pondering some stuff last night and wanted to double check something with you real quick.
> > The C11 atomics API lets you query the implementation via `atomic_is_lock_free()` on an atomic to determine whether it "locks" or not at runtime. The default implementation for the stuff GCC is giving us via `-matomic-model=soft-imask` is all returning `true` there, so that model is clearly considered to be lock-free.
> > The question, though, is now that we're using spinlocks for the generic-case, is that still considered to be a "lock-free" implementation by the C standard, since it's technically non-blocking or do I need to modify that symbol to return `false` for the generic case?
> 
> I'd imagine it wouldn't be proper to say that our implementation is lock free when it isn't. In the grand scheme of things, does it matter? Probably not... But to be proper, it should probably be the case that for any object that would trigger the spinlock case that it should say false for it being lock-free.

Sounds good. I am definitely wanting to do the right thing here.

1) updated back-end and example so that `atomic_is_lock_free()` returns false for our generic case
2) merged back with master
3) fixed a teensy little warning that I must've missed
4) reverified tests, nothing broke

2023-09-15 03:18 UTC, ljsebald requested changes

2023-09-15 03:18 UTC, ljsebald commented on kernel/libc/c11/atomics.c
> +#define GENERIC_LOCK_BLOCK_SIZE     (CPU_CACHE_BLOCK_SIZE * 4)
```suggestion
#define GENERIC_LOCK_BLOCK_SIZE     (CPU_CACHE_BLOCK_SIZE * 4)

```

2023-09-15 03:18 UTC, ljsebald commented on kernel/libc/c11/atomics.c
> +{
```suggestion
                   int memorder) {
```

2023-09-15 03:18 UTC, ljsebald commented on kernel/libc/c11/atomics.c
> +{
```suggestion
                    int memorder) {
```

2023-09-15 03:18 UTC, ljsebald commented on kernel/libc/c11/atomics.c
> +{
```suggestion
                       int memorder) {
```

2023-09-15 03:18 UTC, ljsebald commented on kernel/libc/c11/atomics.c
> +{
```suggestion
                               int fail_memorder) {
```

2023-09-15 03:18 UTC, ljsebald commented on kernel/libc/c11/atomics.c
> +    const uintptr_t lock = address_to_spinlock(ptr);
```suggestion
    bool retval;
    const uintptr_t lock = address_to_spinlock(ptr);

    (void)success_memorder;
    (void)fail_memorder;
```

2023-09-15 03:18 UTC, ljsebald commented on kernel/libc/c11/atomics.c
> +    } else {
```suggestion
    }
    else {
```

2023-09-15 03:18 UTC, ljsebald commented on kernel/libc/c11/atomics.c
> +    const uintptr_t lock = address_to_spinlock(ptr);
```suggestion
    const uintptr_t lock = address_to_spinlock(ptr);

    (void)memorder;

```

2023-09-15 03:18 UTC, ljsebald commented on kernel/libc/c11/atomics.c
> +    const uintptr_t lock = address_to_spinlock(ptr);
```suggestion
    const uintptr_t lock = address_to_spinlock(ptr);

    (void)memorder;
    
```

2023-09-15 03:18 UTC, ljsebald commented on kernel/libc/c11/atomics.c
> +    const uintptr_t lock = address_to_spinlock(ptr);
```suggestion
    const uintptr_t lock = address_to_spinlock(ptr);

    (void)memorder;

```

2023-09-15 03:18 UTC, ljsebald commented on kernel/libc/c11/atomics.c
> +        type ret = *(type *)ptr; \
```suggestion
        const int irq = irq_disable(); \
        type ret = *(type *)ptr; \
        (void)memorder; \
```

2023-09-15 03:18 UTC, ljsebald commented on kernel/libc/c11/atomics.c
> +        type ret = *(type *)ptr; \
```suggestion
        const int irq = irq_disable(); \
        type ret = *(type *)ptr; \
        (void)memorder; \
```

2023-09-15 03:18 UTC, ljsebald commented on kernel/libc/c11/atomics.c
> +        bool retval; \
```suggestion
                                  int failure_memorder) { \
        const int irq = irq_disable(); \
        bool retval; \
        (void)weak; \
        (void)success_memorder; \
        (void)failure_memorder; \
```

2023-09-15 03:18 UTC, ljsebald commented on kernel/libc/c11/atomics.c
> +        const type ret = *(type *)ptr; \
```suggestion
        const int irq = irq_disable(); \
        const type ret = *(type *)ptr; \
        (void)model; \
```

2023-09-15 03:18 UTC, ljsebald commented on kernel/libc/c11/atomics.c
> +        const type ret = *(type *)ptr; \
```suggestion
        const int irq = irq_disable(); \
        const type ret = *(type *)ptr; \
        (void)model; \
```

2023-09-15 03:18 UTC, ljsebald commented on examples/dreamcast/basic/threading/atomics/atomics.c
> +
```suggestion
```

2023-09-15 03:18 UTC, ljsebald commented on examples/dreamcast/basic/threading/atomics/atomics.c
> +      {
```suggestion
                                          true)) { 
```

2023-09-15 03:18 UTC, ljsebald commented on examples/dreamcast/basic/threading/atomics/atomics.c
> +      printf("Thread[%2u]: Acquired atomic bool lock.\n", tid);
```suggestion

      printf("Thread[%2u]: Acquired atomic bool lock.\n", tid);
```

2023-09-15 03:18 UTC, ljsebald commented on examples/dreamcast/basic/threading/atomics/atomics.c
> +      {
```suggestion
                                         false)) {
```

2023-09-15 03:18 UTC, ljsebald commented on examples/dreamcast/basic/threading/atomics/atomics.c
> +      {
```suggestion
      if(thrd_create(&threads[t], thread,
                     (void *)t + 1) != thrd_success) {
```

2023-09-15 03:18 UTC, ljsebald commented on examples/dreamcast/basic/threading/atomics/atomics.c
> +   } else printf("\tFlag atomics work.\n");
```suggestion
   }
   else {
       printf("\tFlag atomics work.\n");
   }
```

2023-09-15 03:18 UTC, ljsebald commented on examples/dreamcast/basic/threading/atomics/atomics.c
> +   {
```suggestion
                                    true)) {
```

2023-09-15 03:18 UTC, ljsebald commented on examples/dreamcast/basic/threading/atomics/atomics.c
> +   {
```suggestion
   if((byte_value = atomic_load(&byte_atomic)) != byte_expected_value) {
```

2023-09-15 03:18 UTC, ljsebald commented on examples/dreamcast/basic/threading/atomics/atomics.c
> +   } else printf("\t8-bit atomics work.\n");
```suggestion
   }
   else {
       printf("\t8-bit atomics work.\n");
   }
```

2023-09-15 03:18 UTC, ljsebald commented on examples/dreamcast/basic/threading/atomics/atomics.c
> +   } else printf("\t16-bit atomics work.\n");
```suggestion
   }
   else {
       printf("\t16-bit atomics work.\n");
   }
```

2023-09-15 03:18 UTC, ljsebald commented on examples/dreamcast/basic/threading/atomics/atomics.c
> +   } else printf("\t32-bit atomics work.\n");
```suggestion
   }
   else {
       printf("\t32-bit atomics work.\n");
   }
```

2023-09-15 03:18 UTC, ljsebald commented on examples/dreamcast/basic/threading/atomics/atomics.c
> +   } printf("\t64-bit atomics work.\n");
```suggestion
   }
   else {
       printf("\t64-bit atomics work.\n");
   }
```

2023-09-15 03:18 UTC, ljsebald commented on examples/dreamcast/basic/threading/atomics/atomics.c
> +   } else printf("\tptrdiff_t atomics work.\n");
```suggestion
   }
   else {
       printf("\tptrdiff_t atomics work.\n");
   }
```

2023-09-15 03:18 UTC, ljsebald commented on examples/dreamcast/basic/threading/atomics/atomics.c
> +   } else printf("\tBool atomics work.\n");
```suggestion
   }
   else {
       printf("\tBool atomics work.\n");
   }
```

2023-09-15 03:18 UTC, ljsebald commented on examples/dreamcast/basic/threading/atomics/atomics.c
> +   {
```suggestion
   if((int_value = atomic_load(&int_atomic)) != int_expected_value) {
```

2023-09-15 03:18 UTC, ljsebald commented on examples/dreamcast/basic/threading/atomics/atomics.c
> +   {
```suggestion
   if((longlong_value = atomic_load(&longlong_atomic)) !=
           THREAD_COUNT * ITERATION_COUNT) {
```

2023-09-15 03:18 UTC, ljsebald commented on examples/dreamcast/basic/threading/atomics/atomics.c
> +   {
```suggestion
   if((short_value = atomic_load(&short_atomic)) !=
           -(THREAD_COUNT * ITERATION_COUNT)) {
```

2023-09-15 03:18 UTC, ljsebald commented on examples/dreamcast/basic/threading/atomics/atomics.c
> +      int_expected_value &= i;
```suggestion
   for(int i = 0; i < THREAD_COUNT; ++i) {
       int_expected_value &= i;
   }
```

2023-09-15 03:18 UTC, ljsebald commented on examples/dreamcast/basic/threading/atomics/atomics.c
> +      byte_expected_value |= i;
```suggestion
   for(unsigned i = 0; i < THREAD_COUNT; ++i) {
       byte_expected_value |= i;
   }
```

2023-09-15 03:18 UTC, ljsebald commented on examples/dreamcast/basic/threading/Makefile
> +# (c) 2002 Megan Potter
```suggestion
# Copyright (C) 2002 Megan Potter
```

2023-09-15 07:16 UTC, gyrovorbis commented
Alrighty,  addressed review changes and retested, because I'm always paranoid. Looking good!

![Screenshot from 2023-09-15 02-14-39](https://github.com/KallistiOS/KallistiOS/assets/5545520/c46b3ee2-ad98-4383-914d-5ecae2cfcc0e)

2023-09-15 19:39 UTC, ljsebald approved these changes

2023-09-15 19:40 UTC, merged