Vmu extra blocks
KallistiOS/KallistiOS pull request #307
Opened 2023-09-17 06:09 UTC by andressbarajas

Add two functions to VMU API:

1. Check the enabled status of a VMUs extra blocks.
2. Enable/Disable the status of the VMUs extra blocks.

2023-09-17 06:16 UTC, gyrovorbis submitted a review, later dismissed
Looks good. I'm very happy to see this, because there's only one mainstream tool out there that can unlock these blocks, and I'd like to see the KOS VMU stuff support all it has to offer. :)

2023-09-17 06:23 UTC, gyrovorbis approved these changes

2023-09-22 03:23 UTC, ljsebald requested changes
I think that it would be more appropriate to be more exacting in the names of these functions. Feel free to comment if anyone has a better idea than what I've suggested here...

2023-09-22 03:23 UTC, ljsebald commented on kernel/arch/dreamcast/hardware/maple/vmu.c
> +int vmu_has_extra_blocks(maple_device_t *dev) {
```suggestion
int vmu_has_241_blocks(maple_device_t *dev) {
```

2023-09-22 03:23 UTC, ljsebald commented on kernel/arch/dreamcast/hardware/maple/vmu.c
> +int vmu_use_extra_blocks(maple_device_t *dev, int enable) {
```suggestion
int vmu_toggle_241_blocks(maple_device_t *dev, int enable) {
```

2023-09-22 03:23 UTC, ljsebald commented on kernel/arch/dreamcast/include/dc/maple/vmu.h
> +int vmu_has_extra_blocks(maple_device_t *dev);
```suggestion
*/
int vmu_has_241_blocks(maple_device_t *dev);
```

2023-09-22 03:23 UTC, ljsebald commented on kernel/arch/dreamcast/include/dc/maple/vmu.h
> +int vmu_use_extra_blocks(maple_device_t *dev, int enable);
```suggestion
*/
int vmu_toggle_241_blocks(maple_device_t *dev, int enable);
```

2023-09-22 04:40 UTC, gyrovorbis commented
> I think that it would be more appropriate to be more exacting in the names of these functions. Feel free to comment if anyone has a better idea than what I've suggested here...

Actually, I think you might be right... Watch us find out we can do VMU sizes bigger than that (TapamN had the BIOS detecting 400 blocks), or watch us add something for VM2 that makes this naming become ambiguous... I think this is the best way to not have our API bite us in the ass at the end.

I also agree with the `vmu_use_extra_blocks()`, being changed to `vmu_toggle_extra_blocks()`, on account of the former sounding like it's only enabling them. I also use the "toggle" nomenclature in my codebase for when the API can either enable or disable something based on a bool, plus this is what Qt does at least.... lol.

2023-09-22 21:01 UTC, ljsebald approved these changes

2023-09-22 21:02 UTC, merged

2023-10-26 16:34 UTC, megavolt85 commented
ladies and gentlemen, there is an excellent command MAPLE_COMMAND_GETMINFO, which provides all the necessary information about VMU, why these crutches?