Garbage-collect network stack
KallistiOS/KallistiOS pull request #329
Opened 2023-10-24 16:41 UTC by pcercuei

Tweak the code so that the network stack (and BBA and LAN adapter code) will be garbage-collected when a KOS program has been compiled without the INIT_NET flag.

This really drops the size of the compiled binaries. For instance, the dreamcast "hello" example dropped from 284 KiB to 156 KiB (both stripped).

Note that this breaks the ABI a bit, as KOS' symbols are not exported anymore by default, and will be exported only if the `INIT_EXPORT` flag has been passed to `KOS_INIT_FLAGS`. This should be fine for the vast majority of programs out there though.

2023-10-28 13:17 UTC, ljsebald requested changes
Just have a few minor style fixes here.

Thank you for taking this on. This is something that's actually been on my mind for a while, but that I hadn't sat down and worked on. Definitely an improvement to cut down on the filesize in this way.

2023-10-28 13:17 UTC, ljsebald commented on kernel/arch/dreamcast/hardware/hardware.c
> +{
```suggestion
void bba_la_init(void) {
```

2023-10-28 13:17 UTC, ljsebald commented on kernel/arch/dreamcast/hardware/hardware.c
> +{
```suggestion
void bba_la_shutdown(void) {
```

2023-10-28 13:17 UTC, ljsebald commented on kernel/arch/dreamcast/hardware/hardware.c
> +	    (*bba_la_init_weak)();
```suggestion
    if(bba_la_init_weak)
        (*bba_la_init_weak)();
```

2023-10-28 13:17 UTC, ljsebald commented on kernel/arch/dreamcast/hardware/hardware.c
> +            if (bba_la_shutdown_weak)
```suggestion
            if(bba_la_shutdown_weak)
```

2023-10-28 13:17 UTC, ljsebald commented on kernel/arch/dreamcast/kernel/init.c
> +{
```suggestion
void arch_init_net(void) {
```

2023-10-28 13:17 UTC, ljsebald commented on kernel/arch/dreamcast/kernel/init.c
> +    if (init_net_weak)
```suggestion
    if(init_net_weak)
```

2023-10-28 13:17 UTC, ljsebald commented on kernel/arch/dreamcast/kernel/init.c
> +	    (*net_shutdown_weak)();
```suggestion
    if(net_shutdown_weak)
        (*net_shutdown_weak)();
```

2023-10-28 13:17 UTC, ljsebald commented on kernel/exports/nmmgr.c
> +	    (*export_init_weak)();
```suggestion
    if(export_init_weak)
        (*export_init_weak)();
```

2023-10-28 13:17 UTC, ljsebald commented on include/kos/init.h
> +	int (*export_init_weak)(void) = ((flags) & INIT_EXPORT) ? export_init : NULL
```suggestion
    uint32 __kos_init_flags = (flags); \
    extern void arch_init_net(void); \
    void (*init_net_weak)(void) = ((flags) & INIT_NET) ? arch_init_net : NULL; \
    extern void net_shutdown(void); \
    void (*net_shutdown_weak)(void) = ((flags) & INIT_NET) ? net_shutdown : NULL; \
    extern void bba_la_init(void); \
    void (*bba_la_init_weak)(void) = ((flags) & INIT_NET) ? bba_la_init : NULL; \
    extern void bba_la_shutdown(void); \
    void (*bba_la_shutdown_weak)(void) = ((flags) & INIT_NET) ? bba_la_shutdown : NULL; \
    extern int export_init(void); \
    int (*export_init_weak)(void) = ((flags) & INIT_EXPORT) ? export_init : NULL
```

2023-10-28 15:13 UTC, pcercuei commented
@ljsebald updated.

2023-10-29 21:15 UTC, ljsebald submitted a review, later dismissed

2023-10-29 21:15 UTC, ljsebald commented on kernel/exports/nmmgr.c
> +    if (export_init_weak)
```suggestion
    if(export_init_weak)
```

2023-10-29 21:15 UTC, merged