Modularizing KOS, my take
KallistiOS/KallistiOS pull request #360
Opened 2023-11-12 12:26 UTC by pcercuei

A rewrite of https://github.com/KallistiOS/KallistiOS/pull/335.

The bulk of the changes are by GyroVorbis, so he should probably sign-off the commits as well (or give me the permission to add his sign-off).

Compiling the "hello" example with just `KOS_INIT_FLAGS(INIT_IRQ | INIT_THD_PREEMPT | INIT_MALLOCSTATS | INIT_FS_ROMDISK);`, in which case the maple code and VMU FS code are garbage-collected, the resulting (stripped) hello.elf drops from 156 KiB to 120 KiB.

2023-11-15 19:53 UTC, gyrovorbis approved these changes
Looks good. This is definitely the PR we want over my old one. Cleaned up a bunch of stuff, made `maple_wait_scan()` only get called when at least one maple device is enabled, changed `likely` and `unlikely` to match the Linux macros, etc.

2023-11-22 03:55 UTC, ljsebald requested changes
One tiny formatting fixup...

2023-11-22 03:55 UTC, ljsebald commented on include/kos/init.h
> + #define INIT_FS_ROMDISK  0x00000040  /**< \brief Enable support for romdisks */
```suggestion
#define INIT_DEFAULT    (INIT_IRQ | INIT_THD_PREEMPT | INIT_FS_ROMDISK | \
                         INIT_DEFAULT_ARCH)

#define INIT_NONE        0x00000000  /**< \brief Don't init optional things */
#define INIT_IRQ         0x00000001  /**< \brief Enable IRQs at startup */
/* Preemptive mode is the only mode now. Keeping define for compatability. */
#define INIT_THD_PREEMPT 0x00000002  /**< \deprecated Already default mode */
#define INIT_NET         0x00000004  /**< \brief Enable built-in networking */
#define INIT_MALLOCSTATS 0x00000008  /**< \brief Enable malloc statistics */
#define INIT_QUIET       0x00000010  /**< \brief Disable dbgio */
#define INIT_EXPORT      0x00000020  /**< \brief Export kernel symbols */
#define INIT_FS_ROMDISK  0x00000040  /**< \brief Enable support for romdisks */
```

2023-11-22 04:01 UTC, gyrovorbis reviewed
Crap just saw a couple things I missed before.

2023-11-22 04:01 UTC, gyrovorbis commented on include/kos/init.h
>  /** \brief  The init flags. Do not modify this directly! */
```suggestion
/** \cond */
```

2023-11-22 04:01 UTC, gyrovorbis commented on include/kos/init.h
```suggestion
/** \endcond */

```

2023-11-22 09:58 UTC, pcercuei commented
Updated and force-pushed.

2023-11-22 14:30 UTC, ljsebald approved these changes

2023-11-22 14:31 UTC, merged