UBC Driver Upgrade
KallistiOS/KallistiOS pull request #416
Opened 2023-12-17 20:16 UTC by gyrovorbis

It dawned on me how useful the UBC could be for debugging, and how little of its power we have exposed publicly in our API.

- Huge driver upgrade and new APIs which expose everything it's actually capable of doing
- Bunch of new documentation explaining what the heck a UBC is and why it's useful
- Will create a really good user-example for debugging with the UBC
- UBC is used internally by the GDB stub; however, rather than using the UBC driver, it creates its own inner API duplicating things and potentially interfering with outside usage. I'm planning to make GDB use the actual UBC driver.

2024-01-21 05:27 UTC, andressbarajas commented on examples/dreamcast/basic/breaking/breaking.c
> +            .address_mask = ubc_address_mask_10, // don't care aabout lower 10 bits
```suggestion
            .address_mask = ubc_address_mask_10, // don't care about lower 10 bits
```

2024-01-21 05:28 UTC, andressbarajas commented on examples/dreamcast/basic/breaking/breaking.c
> +    VERIFY(!handled_); //we accessed it as the wrong size
```suggestion
    VERIFY(!handled_); // we accessed it as the wrong size
```

2024-01-21 05:28 UTC, andressbarajas commented on examples/dreamcast/basic/breaking/breaking.c
> +    VERIFY(!handled_); //we only did a read
```suggestion
    VERIFY(!handled_); // we only did a read
```

2024-01-21 05:35 UTC, andressbarajas commented on kernel/arch/dreamcast/include/dc/ubc.h
> +    Typedef for the user function to be invoked upon a encountering a
```suggestion
    Typedef for the user function to be invoked upon encountering a
```

2024-01-29 00:47 UTC, ljsebald requested changes

2024-01-29 00:47 UTC, ljsebald commented on kernel/arch/dreamcast/hardware/ubc.c
> +    }
```suggestion
    switch(addr_mask) {
        case ubc_address_mask_all:
            return 3;
        case ubc_address_mask_16:
            return 4;
        case ubc_address_mask_20:
            return 5;
        default:
            return addr_mask;
    }
```

2024-01-29 00:47 UTC, ljsebald commented on kernel/arch/dreamcast/hardware/ubc.c
> +
```suggestion
```

2024-01-29 00:47 UTC, ljsebald commented on kernel/arch/dreamcast/hardware/ubc.c
> +
```suggestion
```

2024-01-29 00:47 UTC, ljsebald commented on kernel/arch/dreamcast/hardware/ubc.c
> +    bool serviced = false;
```suggestion
    bool serviced = false;

    (void)code;
```

2024-01-29 00:47 UTC, ljsebald commented on kernel/arch/dreamcast/hardware/ubc.c
> +                        );
```suggestion
            disable = channel_state[ubc_channel_b].cb(
                            channel_state[ubc_channel_b].bp,
                            irq_ctx,
                            channel_state[ubc_channel_b].ud);
```

2024-01-29 00:47 UTC, ljsebald commented on kernel/arch/dreamcast/hardware/ubc.c
> +
```suggestion
```

2024-01-29 00:47 UTC, ljsebald commented on kernel/arch/dreamcast/hardware/ubc.c
> +                            );
```suggestion
                disable = channel_state[ubc_channel_a].cb(
                                channel_state[ubc_channel_a].bp,
                                irq_ctx,
                                channel_state[ubc_channel_a].ud);
```

2024-01-29 02:18 UTC, ljsebald commented on examples/dreamcast/basic/breaking/breaking.c
> +}
```suggestion
}

```

2024-01-29 02:19 UTC, gyrovorbis commented
Retested after addressing review feedback + resolving conflicts, and everything is still working great!

2024-01-29 02:19 UTC, ljsebald approved these changes

2024-01-29 02:21 UTC, merged