Increased Resolution of C's clock() and CLOCKS_PER_SEC to Microseconds
KallistiOS/KallistiOS pull request #423
Opened 2023-12-19 23:15 UTC by gyrovorbis

- Added #define to kos/time.h to provide newlib with an initial value for CLOCKS_PER_SEC
- Modified newlib_times.c to use the microsecond timer, which is what backs the clock() C stdlib function
- Updated CHANGELOG

2023-12-19 23:18 UTC, andrewapperley approved these changes
Looks good to me! Easy enough change.

2023-12-20 20:10 UTC, ljsebald commented on doc/CHANGELOG
> +- DC  Increased resolution of C's clock() and CLOCKS_PERS_SEC to microseconds [FG]
```suggestion
- DC  Increased resolution of clock() and CLOCKS_PER_SEC to microseconds [FG]
```

2023-12-20 20:10 UTC, ljsebald requested changes
See above.

2023-12-20 22:04 UTC, gyrovorbis commented
> Merging is blocked
> Merging can be performed automatically once the requested changes are addressed.

Oh yeah, good point. Addressed.

2023-12-21 01:38 UTC, gyrovorbis commented
> See above.

Actually, based on that comment, is the above entry in the CHANGELOG not also incorrect? TMU and stdlib crap would also not be DC-specific, would it?

2023-12-21 05:00 UTC, ljsebald commented
> > See above.
> 
> Actually, based on that comment, is the above entry in the CHANGELOG not also incorrect? TMU and stdlib crap would also not be DC-specific, would it?

TMU is certainly DC-specific. This change changes nothing in the arch/dreamcast directory and only changes things in the supposedly non-arch-specific directories, hence marking it not as DC only.

That said, the distinction is kinda moot, since there aren't any other arches anyway.

2023-12-21 06:13 UTC, gyrovorbis commented
OOOOOH. I keep getting the subarch confused with the architecture. In my mind, the `TMU` stuff was "architecture-independent" for being also a change that would've influenced NAOMI. Now it all makes sense. :)

2023-12-23 04:19 UTC, ljsebald approved these changes

2023-12-23 04:19 UTC, merged