Updated dc-chain for DLang +  BETA m4-single support
KallistiOS/KallistiOS pull request #518
Opened 2024-04-21 04:58 UTC by gyrovorbis

- Added an option for D to the pass2 langauges list, with a note that dependencies must already have been installed.
- Added `--disable-libphobos` flag to the pass2 script to prevent it from being built with D (required for D to build properly), but it's also gracefully ignored without D.
- Added `-m4-single` to the default list of FP configurations to build WHILE STILL KEEPING a strict warning about early beta support for it.

@darcagn If you've reviewed this, can you help me port these changes to your other configs? Or at very least the new GCC14 config, I guess.

2024-04-21 21:27 UTC, ljsebald commented
> Why not switch completely to `-m4-single`? YOLO :)

Absolutely not. I will not allow that switch at this point.

2024-04-21 22:25 UTC, gyrovorbis commented
> > Why not switch completely to `-m4-single`? YOLO :)
> 
> 
> 
> Absolutely not. I will not allow that switch at this point.

Omg I was literally about to respond with "...because Crabby will have our heads!" Lmao.

I did want to make it something that gets built by default, though, because I'm seeing people wanting it for raylib (does the double time step shenanigans that objective-c did), PLUS -m4-single-only is literally broken with C++23 (compiler ICE, already reported). 

Just seeing the same pattern of "darn I didn't know I needed to enable that in the config file!" stuff I was seeing with people missing the c99 formatters awhile back.

2024-04-21 23:10 UTC, darcagn commented
IMO I'm in support of having support for it built by default. Some things require `-m4-single-only` to work and some things require `-m4-single` so it seems reasonable now to just build both.

2024-04-26 11:10 UTC, pcercuei commented
@darc what requires `-m4-single-only`?

2024-04-26 20:24 UTC, ljsebald commented
> @darc what requires `-m4-single-only`?

KOS.

2024-04-26 20:25 UTC, ljsebald requested changes
Spelling correction.

2024-04-26 20:25 UTC, ljsebald commented on utils/dc-chain/config/config.mk.13.2.1-dev.sample
> +# with m4-single-only to save disc space.
```suggestion
# with m4-single-only to save disk space.
```

2024-04-26 20:30 UTC, ljsebald approved these changes
Approved, although gonna let @darcagn deal with merging and such (since this is really his domain).

2024-04-26 21:11 UTC, pcercuei commented
> > @darc what requires `-m4-single-only`?
> 
> KOS.

What in KOS requires `-m4-single-only`?

2024-04-26 22:12 UTC, darcagn commented
> @darc what requires `-m4-single-only`?

As I understand it there are some kos-ports that need adjusting but I don't know which ones exactly. GLdc was one of them but is fixed now, there are likely others. This needs testing. 

As far as KOS itself goes there are no *known* bugs or incompatibilities, but testing is only to the extent that a handful of people have been using it in their normal course of use lately. It's certainly not a complete coverage for testing. 

I want to switch to `-m4-single` by default too but we really should make a release before we introduce any more stuff that would break third party code. Then IMO we can run wild. In the mean time since there's more and more stuff relying on it (Raylib, Rust, Foundation, Fortran, etc.) it makes sense to build support and offer the option. With this PR it's trivial now.

2024-04-26 22:40 UTC, darcagn commented
Tested and `--disable-libphobos` is still gracefully ignored back in 4.7.4, so I'll go ahead and merge this.

2024-04-26 22:40 UTC, merged