Implemented C23 stdlib features for <time.h>
KallistiOS/KallistiOS pull request #550
Opened 2024-05-06 04:44 UTC by gyrovorbis

- New macro for C23 compliance of the file
- Macros were redone to check for existence of C and C++ macros before "dereferencing"
- New C23 time base types
- `asctime()` and `ctime()` are now deprecated in C23
- C23 added `timespec_getres()` for getting resolution of a time base
- C23 added `gmtime_r()` and `localtime_r()` reentrant time converters
- Implemented timespec API by mapping it directly to POSIX clock API
- Removed `clock_gettime()`'s reliance on timespec_get() for CLOCK_REALTIME, so that the dependency could be reversed.
- Removed whitespace from RTC
- Enabling C23 compatibility in C++23, regardless of whether the C++ standards commitee gets off its ass ever and does interop, because I queried a bunch of devs, and they think it's "good guy" stdlib thing to do.... lol.

2024-05-07 17:58 UTC, gyrovorbis commented on include/kos/time.h
> +   #ifndef _POSIX_THREAD_CPU_TIME
Good catch, my friend!!!

2024-05-18 01:27 UTC, gyrovorbis commented
Now that the Per-thread CPU time PR has been merged, I've enabled this in C23 via the `timespec_get()` API as well.

2024-06-05 03:36 UTC, ljsebald requested changes

2024-06-05 03:36 UTC, ljsebald commented on kernel/libc/c11/timespec_get.c
> +}
Why is this in this file? Please move it to its own file.

2024-06-05 03:36 UTC, ljsebald commented on include/kos/time.h
> +   #define TIME_UTC 1
Please don't indent things in like this inside #if blocks. We don't do that anywhere else in the code, so please don't do it here. And **especially** don't indent it by 3 spaces like this.

Note: this applies to the rest of the file too, of course.

2024-06-06 00:52 UTC, ljsebald commented on kernel/libc/c11/timespec_get.c
> +}
```suggestion
}

```

2024-06-06 00:52 UTC, ljsebald approved these changes

2024-06-06 00:53 UTC, merged