Cleanups to shutdown memory
KallistiOS/KallistiOS pull request #599
Opened 2024-05-29 20:11 UTC by QuzarDC

These resolve a series of issues I have found while attempting to debug malloc behavior.

- Check if the current thread is null before derefing to get its tid when KM_DBG is set. Now in `malloc_stats()` and malloc debug output thread tid 0 represents memory allocated when no threading is running.
- Correct header issues and warnings that prevented malloc_debug from building.
- Shutdown threading using the destroy function to free threads rather than manually removing individual pieces of their data. This stops TLS allocations from leaking.

2024-05-29 20:20 UTC, QuzarDC commented
Of note, if I set the verbose debug on malloc it seems to either crash or lock up immediately. Additionally I am still seeing though with the 9.3.0 toolchain that data is leaking (though not with 15.0.0) in just the plain hello example with `INIT_MALLOCSTATS` enabled.
![image](https://github.com/KallistiOS/KallistiOS/assets/686781/58090977-6180-47a1-a13b-f57c19e05100)

I believe the size 12 calloc is the allocation of the rootfs fh here: https://github.com/KallistiOS/KallistiOS/blob/edcd7615c1d7ef0c88f8c0e601b9e11668b010e8/kernel/fs/fs.c#L55-L57 which, it makes sense that it would be leaked, but it doesn't make sense that it would even be accessed at all in hello world.

I don't think I'll actually be solving all these before setting this to ready, but wanted to take some extra notes to spin off different issues.

2024-05-29 22:58 UTC, andressbarajas commented
Here is the issue about the KM_DBG_VERBOSE crash/lockup: https://github.com/KallistiOS/KallistiOS/issues/290

2024-05-30 21:24 UTC, QuzarDC commented
> Here is the issue about the KM_DBG_VERBOSE crash/lockup: #290

Thanks for that, I wasn't aware. Added a touchup to the dbglog core that I thought might help avoid possible mallocs inside the debug output, but it didn't seem to make a difference.

2024-05-31 03:00 UTC, andressbarajas commented
@QuzarDC What are the best examples to test this with?

2024-05-31 03:12 UTC, QuzarDC commented
> @QuzarDC What are the best examples to test this with?

Unfortunately most of it is internal/debug paths or the shutdown paths. I actually walked through about a dozen of our examples enabling `INIT_MALLOCSTATS` to see the impact before/after (before, it would show more memory still 'in use'). I've actually got a separate PR that I held back from this one with all the examples that I also made sure to add proper cleanups to (closing files and freeing memory).

I think anything with lots of file I/O and text out would likely be the best since those are the kinds of public paths most changed here. Testing out building anything with KM_DBG set would also be good to work out the cleanups in there.

2024-05-31 23:31 UTC, QuzarDC commented
Figured out how to fix the KM_DBG_VERBOSE issue, so going to polish that up and fold it into the existing changes here since they're all so related.

2024-06-01 04:42 UTC, andressbarajas commented on kernel/libc/koslib/malloc.c
> +int mem_check_block_int(memctl_t * ctl, int source) {
```suggestion
int mem_check_block_int(memctl_t *ctl, int source) {
```

2024-06-01 04:42 UTC, andressbarajas commented on kernel/libc/koslib/malloc.c
> +void dbg_print_thd_addr_action(tid_t thread, uint32 addr, void* m, size_t s, uint8 which) {
```suggestion
void dbg_print_thd_addr_action(tid_t thread, uint32 addr, void *m, size_t s, uint8_t which) {
```

2024-06-01 04:43 UTC, andressbarajas commented on kernel/libc/koslib/malloc.c
> +static const char * func_type[8] =
```suggestion
static const char *func_type[8] =
```

2024-06-05 02:45 UTC, ljsebald requested changes
Just a few minor things that I noticed....

2024-06-05 02:45 UTC, ljsebald commented on kernel/arch/dreamcast/fs/fs_dcload.c
> +    no change since it already holds 0 as 'no mem assigned */
```suggestion
      no change since it already holds 0 as 'no mem assigned */
```

2024-06-05 02:45 UTC, ljsebald commented on kernel/libc/koslib/dbglog.c
> +    i= vsnprintf(printf_buf, sizeof(printf_buf), fmt, args);
```suggestion
    i = vsnprintf(printf_buf, sizeof(printf_buf), fmt, args);
```

2024-06-05 02:50 UTC, ljsebald approved these changes

2024-06-05 02:51 UTC, merged