vmu_pkg: Add function to load VMU icons from .ico files
KallistiOS/KallistiOS pull request #873
Opened 2024-12-23 13:12 UTC by pcercuei

Add the function vmu_pkg_load_icon(), which can load a VMU save icon from a .ico file.
    
Icon files must be in the ICO file format, be 32x32 in size, contain a bitmap (no PNG or compressed BMP), and use paletted 4bpp. They can contain more than one frame, and they can use up to 16 colors if transparency is not used, or 15 colors otherwise. Finally, all frames must use the same palette.
    
This function assumes that the vmu_pkg_t has been properly initialized; in particular, the .icon_cnt must be set, and the .icon_data must point to a valid buffer (of 512 bytes per frame).
    
If the .ico file contains more frames than requested, only the first ones are loaded. If it contains less frames than requested, the .icon_cnt field will be updated to the new frame count.

The dreamcast/vmu_pkg/ example was also updated, and the saved file now has an icon (drawn by myself).

2024-12-24 03:46 UTC, ljsebald requested changes
A few formatting fixes for now...

2024-12-24 03:46 UTC, ljsebald commented on kernel/arch/dreamcast/util/vmu_pkg.c
> +            if (curr_pal[i] == pal[j])
```suggestion
    for(i = 0; i < 16; i++) {
        for(j = 0; j < nb_colors; j++)
            if(curr_pal[i] == pal[j])
```

2024-12-24 03:46 UTC, ljsebald commented on kernel/arch/dreamcast/util/vmu_pkg.c
> +        if (nb_colors == 15) {
```suggestion
        if(j < nb_colors) {
            /* Found the color in our palette */
            map[i] = j;
            continue;
        }

        if(nb_colors == 15) {
```

2024-12-24 03:46 UTC, ljsebald commented on kernel/arch/dreamcast/util/vmu_pkg.c
> +        | ((px >> 4) & 0x000f);
```suggestion
    return 0xf000 |
        ((px >> 12) & 0x0f00) |
        ((px >> 8) & 0x00f0) |
        ((px >> 4) & 0x000f);
```

2024-12-24 03:46 UTC, ljsebald commented on kernel/arch/dreamcast/util/vmu_pkg.c
> +    for (i = 0; i < nb_colors; i++)
```suggestion
    for(i = 0; i < nb_colors; i++)
```

2024-12-24 03:46 UTC, ljsebald commented on kernel/arch/dreamcast/util/vmu_pkg.c
> +    if (!pkg->icon_cnt || !pkg->icon_data) {
```suggestion
    if(!pkg->icon_cnt || !pkg->icon_data) {
```

2024-12-24 03:46 UTC, ljsebald commented on kernel/arch/dreamcast/util/vmu_pkg.c
> +    if (fd == -1)
```suggestion
    if(fd == -1)
```

2024-12-24 03:46 UTC, ljsebald commented on kernel/arch/dreamcast/util/vmu_pkg.c
> +    if (hdr.resv != 0 || hdr.type != 1) {
```suggestion
    if(hdr.resv != 0 || hdr.type != 1) {
```

2024-12-24 03:46 UTC, ljsebald commented on kernel/arch/dreamcast/util/vmu_pkg.c
> +    if (hdr.nb_images < pkg->icon_cnt)
```suggestion
    if(hdr.nb_images < pkg->icon_cnt)
```

2024-12-24 03:46 UTC, ljsebald commented on kernel/arch/dreamcast/util/vmu_pkg.c
> +    if (hdr.nb_images > pkg->icon_cnt) {
```suggestion
    if(hdr.nb_images > pkg->icon_cnt) {
```

2024-12-24 03:46 UTC, ljsebald commented on kernel/arch/dreamcast/util/vmu_pkg.c
> +    for (i = 0; i < hdr.nb_images; i++) {
```suggestion
    for(i = 0; i < hdr.nb_images; i++) {
```

2024-12-24 03:46 UTC, ljsebald commented on kernel/arch/dreamcast/util/vmu_pkg.c
> +        if (dir->width != 32 || dir->height != 32 || dir->bpp != 4) {
```suggestion
        if(dir->width != 32 || dir->height != 32 || dir->bpp != 4) {
```

2024-12-24 03:46 UTC, ljsebald commented on kernel/arch/dreamcast/util/vmu_pkg.c
> +    for (i = 0; i < (unsigned int)pkg->icon_cnt; i++) {
```suggestion
    for(i = 0; i < (unsigned int)pkg->icon_cnt; i++) {
```

2024-12-24 03:46 UTC, ljsebald commented on kernel/arch/dreamcast/util/vmu_pkg.c
> +        if (dib.hdr_size != 40) {
```suggestion
        if(dib.hdr_size != 40) {
```

2024-12-24 03:46 UTC, ljsebald commented on kernel/arch/dreamcast/util/vmu_pkg.c
> +        if (dib.comp != 0) {
```suggestion
        if(dib.comp != 0) {
```

2024-12-24 03:46 UTC, ljsebald commented on kernel/arch/dreamcast/util/vmu_pkg.c
> +        if (dir->width != 32 || dir->height != 32 || dir->bpp != 4) {
It might also be nice if these were all split out on their own to be more explicit as to what the error is.

2024-12-24 03:46 UTC, ljsebald commented on kernel/arch/dreamcast/util/vmu_pkg.c
> +        if (!nb_colors) {
```suggestion
        if(!nb_colors) {
```

2024-12-24 03:46 UTC, ljsebald commented on kernel/arch/dreamcast/util/vmu_pkg.c
> +            for (x = 0; x < 16; x += 4) {
```suggestion
        for(y = 0; y < 32; y++) {
            for(x = 0; x < 16; x += 4) {
```

2024-12-24 03:46 UTC, ljsebald commented on kernel/arch/dreamcast/util/vmu_pkg.c
> +                for (j = 0; j < 4; j++) {
```suggestion
                for(j = 0; j < 4; j++) {
```

2024-12-24 03:46 UTC, ljsebald commented on kernel/arch/dreamcast/util/vmu_pkg.c
> +                    if (and_mask & BIT(7 - j * 2))
```suggestion
                    if(and_mask & BIT(7 - j * 2))
```

2024-12-24 03:46 UTC, ljsebald commented on kernel/arch/dreamcast/util/vmu_pkg.c
> +                    if (and_mask & BIT(6 - j * 2))
```suggestion
                    if(and_mask & BIT(6 - j * 2))
```

2025-01-03 21:00 UTC, pcercuei commented
@ljsebald done.

@gyrovorbis I'm not sure that's needed in the API, given that an icon is always a fixed-size 32x32 4bpp. I added some defines to the example to make it more explicit though.

2025-02-04 20:40 UTC, ljsebald approved these changes

2025-02-04 20:42 UTC, merged